organizer_app/config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :guests
    root                'static_pages#home'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'guest'   => 'guest#index'
    get    'wedding' => 'static_pages#wedding'
    get    'church'  => 'static_pages#church'
    get    'bride'   => 'static_pages#bride'
    get    'groom'   => 'static_pages#groom'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :password_resets,     only: [:new, :create, :edit, :update]











end

organizer_app/app/models/guest.rb
class Guest < ActiveRecord::Base
end

organizer_app/app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:imie, :nazwisko, :numer, :osobatow)
    end
end

organizer_app/app/helpers/guests_helper.rb
module GuestsHelper
end

organizer_app/app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :imie, "Imie" %><br>
    <%= f.text_field :imie %>
  </p>

  <p>
    <%= f.label :nazwisko, "Nazwisko" %><br>
    <%= f.text_field :nazwisko %>
  </p>

  <p>
    <%= f.label :numer, "Numer" %><br>
    <%= f.text_field :numer %>
  </p>

  <p>
    <%= f.label :osobatow, "Osoba towarzysząca" %><br>
    <%= f.text_field :osobatow %>
  </p>
 <br>
  <p>
    <%= f.submit class: 'btn btn-info custom' %>
 </p>

<% end %>

organizer_app/app/views/guests/edit.html.erb
<h1>Edytuj gościa</h1>
<br>
<%= render 'form' %>
<br>
<p style="text-indent: 6em;">

<%= link_to 'Pokaż', @guest %> |
<%= link_to 'Wstecz', guests_path %>
</p>

organizer_app/app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goście</h1>
<br>
<h4><p style="text-indent: 6em;"><%= link_to 'Nowy Gość', new_guest_path %></p></h4>
<br>
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Numer</th>
      <th>Osoba towarzysząca</th>
      <th colspan="3">Opcje</th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.imie %></td>
        <td><%= guest.nazwisko %></td>
        <td><%= guest.numer %></td>
        <td><%= guest.osobatow %></td>
        <td><%= link_to 'Pokaż', guest %></td>
        <td><%= link_to 'Edytuj', edit_guest_path(guest) %></td>
        <td><%= link_to 'Usuń', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

organizer_app/app/views/guests/new.html.erb
<h1>Nowy gość</h1>


<%= render 'form' %>

<br>
<p style="text-indent: 6em;">
<%= link_to 'Wstecz', guests_path %>
</p>

organizer_app/app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<br>
<br>
<p>
  <strong>Imie:</strong>
  <%= @guest.imie %>
</p>

<p>
  <strong>Nazwisko:</strong>
  <%= @guest.nazwisko %>
</p>

<p>
  <strong>Numer:</strong>
  <%= @guest.numer %>
</p>

<p>
  <strong>Osoba towarzysząca:</strong>
  <%= @guest.osobatow %>
</p>
<br>
<p style="text-indent: 6em;">
<%= link_to 'Edytuj', edit_guest_path(@guest) %> |
<%= link_to 'Wstecz', guests_path %>
</p>