organizer_app/config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :guests
    root                'static_pages#home'
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'guest'   => 'guest#index'
    get    'wedding' => 'static_pages#wedding'
    get    'church'  => 'static_pages#church'
    get    'bride'   => 'static_pages#bride'
    get    'groom'   => 'static_pages#groom'
    get    'signup'  => 'users#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :users
    resources :password_resets,     only: [:new, :create, :edit, :update]











end

organizer_app/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><%= link_to "Organizer ślubny", root_path, id: "logo" %></a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Strona domowa", root_path %></li>
        <li><%= link_to "Pomoc", help_path %></li>
        <li><%= link_to "O stronie", about_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  Konto <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profil", current_user %></li>
                  <li><%= link_to "Ustawienia", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Wyloguj", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Zarejestruj", signup_path %></li>
          <li><%= link_to "Zaloguj", login_path %></li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

organizer_app/app/views/layouts/_sidenav.html.erb

  <% if logged_in? %>
    <ul class="topnav">
        <li><%= link_to "Goście", guests_path %></li>
        <li><%= link_to "Wesele", wedding_path %></li>
        <li><%= link_to "Kościoł", church_path %></li>
        <li><%= link_to "Pan Młody", groom_path %></li>
        <li><%= link_to "Panna Młoda", bride_path %></li>
      </ul>
  <% end %>

organizer_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  <meta charset="utf-8">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/sidenav' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
         <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>